### ISSUE TITLE
Doesn't read fzf.vim config

### ISSUE THREAD

**Issue by nguyenhai97** [LumaKernel/fern-mapping-fzf.vim#4]
For now this plugin does not read fzf config like g:fzf_action and g:fzf_preview_window which make the experience of using it not quite satisfy, hope you could add this function to your plugin

**Comment by LumaKernel** [comment]
Hi, `g:fzf_action` looks nice! I may have supported by https://github.com/LumaKernel/fern-mapping-fzf.vim/pull/5.
On the other hand, `g:fzf_preview_window` is not core `fzf` future, namely that is supported by `fzf.vim`, then I want users plug that in by themselves.
I've made new option `g:Fern_mapping_fzf_customize_option` by https://github.com/LumaKernel/fern-mapping-fzf.vim/pull/5 , so you might use that like following.

```
  function! Fern_mapping_fzf_customize_option(spec)
    return fzf#vim#with_preview(a:spec)
  endfunction
```

**Comment by nguyenhai97** [comment]
While fzf_action did work, it open split above and right to Fern buffer which not intuitive (new buffers are too small since it over lap Fern space which only take 30% in my setup), about the g:Fern_mapping_fzf_customize_option, could you be more specific about how can I use it because I paste the function in init.vim but still I can't see any preview
Sorry for asking too much but I'm just start with vim and doesn't have much vimscript experiences, respect your work

**Comment by LumaKernel** [comment]
> While fzf_action did work, it open split above and right to Fern buffer which not intuitive (new buffers are too small since it over lap Fern space which only take 30% in my setup)

Hm, are you using drawer mode or not? Drawer mode fern.vim buffer is set as fixed size. Optoins like `winfixwidth` may be involved. I'm usually fern buffer mode, and it looks nicely working.

> about the g:Fern_mapping_fzf_customize_option, could you be more specific about how can I use it because I paste the function in init.vim but still I can't see any preview

Thank you for checking, the old one was little buggy, now it may be fixed! The code I wrote may work fine now.

**Comment by LumaKernel** [comment]
Please reopen if you find any problem.

**Comment by LumaKernel** [comment]
https://github.com/LumaKernel/fern-mapping-fzf.vim/pull/5#issuecomment-770408934

Sorry, I am also not an expert. Would you fill followings and let me know your environment at first?

- OS:
- vim or nvim:
- vim or nvim version:
- fzf version (`!fzf --version`):
- fzf options you are using:
  - `g:fzf_action`: 
  - `g:fzf_preview_window`: 
  - `echo $FZF_DEFAULT_OPTS`: 
- How do you install your plugins:
- Can you show me full `init.vim` settings?
- When can you see your preview window? With what command?

In shortly, you may use `$FZF_DEFAULT_OPTS` easily.

**Comment by nguyenhai97** [comment]
OS: Arch linux
vim or nvim: Neovim nightly
vim or nvim version: 0.5.0
fzf version (!fzf --version): 0.25.0 (8c533e3)
fzf options you are using: Will provide in init.vim
g:fzf_action: Will provide in init.vim
g:fzf_preview_window: Will provide in init.vim
echo $FZF_DEFAULT_OPTS: It's not set yet 
How do you install your plugins: I'm using Plug
My init.vim: https://paste.ee/p/CyQoB
When can you see your preview window? With what command?: I can see my preview with fzf.vim, with your plugin I try to view it with ff keybinding but not work (already toggle preview hidden), I tried both command that you give which is this:
```
  function! Fern_mapping_fzf_customize_option(spec)
    return fzf#vim#with_preview(a:spec)
  endfunction
```
and this;
```
  function! Fern_mapping_fzf_customize_option(spec)
    let a:spec.options .= ' --multi'
    return a:spec
  endfunction
```
Seperately and neither of them work. Also I'm using Fern in -drawer mode and the current way that your plugin open new buffer still odd since it tend to put buffer in the left and top of Fern drawer buffer while it should put it to the right and top right (if needed) It work as expected in Fern with action-open and action-split if it not possible to open it correctly then maybe you could do it like coc do, in coc-explorer fzf only bring cursor to the file that we searching for rather how to open it are left to user to manually type the command in and Fern will deal with it (less headache)

**Comment by LumaKernel** [comment]
Nice. We cannot use normal `edit` family for drawer mode fern. Fern `open:...` family may behave nicely using technically different approach. Achieve to use them, we might want to use Fern's one. `g:fzf_action` doesn't suit this purpose. I will add new features to achieve this by https://github.com/LumaKernel/fern-mapping-fzf.vim/pull/6 . After merging this, you can use settings like Example2.

Second problem, `g:fzf_preview_window` setting you are using works for me. At first it's hidden, and hitting `ctrl-/`  will show me a preview window.
You are ought to use this. And also please check  you are not forgetting to update this plugin.

```
  function! Fern_mapping_fzf_customize_option(spec)
    return fzf#vim#with_preview(a:spec)
  endfunction
```

Or also you want to make multiple ones selectable, please see Example2's `Fern_mapping_fzf_customize_option`.

**Comment by nguyenhai97** [comment]
Confirm problem with preview being solved. Also could you prevent  #6 from launching new buffer right away, since I want to open it as other mode as well

**Comment by LumaKernel** [comment]
How about omitting `Fern_mapping_fzf_after_all`?

**Comment by nguyenhai97** [comment]
Omitting it did the trick =)) sorry for not read everything thoroughly just now I notice that function call open:vsplit

**Comment by LumaKernel** [comment]
Never mind. I'm worrying what is better way to provide and illustrate more examples/samples to configure this plugin.
Splitting the options you finally got as plugin looks one good way.

For the time being, merge applicable PR. Thank you for your quick responses.

**Comment by LumaKernel** [comment]
Final form of settings developed here is really nice. I added them in README. Thank you.

**Comment by nguyenhai97** [comment]
Thank for helping and adding solutions in a quick manner 😁 highly appreciate your work and dedication
